apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway-service
  ports:
  - protocol: "TCP"
    port: 8081
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service
spec:
  selector:
    matchLabels:
      app: api-gateway-service
  replicas: 3
  template:
    metadata:
      labels:
        app: api-gateway-service
    spec:
      containers:
      - name: api-gateway-service
        image: chan29/api-gateway:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80