//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoyaltyOnlineWSLogin
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.retalix.com/HQLWebServices", ConfigurationName="LoyaltyOnlineWSLogin.LoginSoap")]
    public interface LoginSoap
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.retalix.com/HQLWebServices/UserLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LoyaltyOnlineWSLogin.UserLoginResponse> UserLoginAsync(LoyaltyOnlineWSLogin.UserLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.retalix.com/HQLWebServices/LogOut", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task LogOutAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.retalix.com/HQLWebServices")]
    public partial class Status
    {
        
        private ReMAEStatusType status1Field;
        
        private string sourceField;
        
        private string messageField;
        
        private string stackTraceField;
        
        private int errorCodeField;
        
        private bool errorCodeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Status")]
        public ReMAEStatusType Status1
        {
            get
            {
                return this.status1Field;
            }
            set
            {
                this.status1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StackTrace
        {
            get
            {
                return this.stackTraceField;
            }
            set
            {
                this.stackTraceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ErrorCodeSpecified
        {
            get
            {
                return this.errorCodeFieldSpecified;
            }
            set
            {
                this.errorCodeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.retalix.com/HQLWebServices")]
    public enum ReMAEStatusType
    {
        
        /// <remarks/>
        Ok,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        SessionNoValid,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserLogin", WrapperNamespace="http://www.retalix.com/HQLWebServices", IsWrapped=true)]
    public partial class UserLoginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.retalix.com/HQLWebServices", Order=0)]
        public string in_UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.retalix.com/HQLWebServices", Order=1)]
        public string in_Password;
        
        public UserLoginRequest()
        {
        }
        
        public UserLoginRequest(string in_UserName, string in_Password)
        {
            this.in_UserName = in_UserName;
            this.in_Password = in_Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserLoginResponse", WrapperNamespace="http://www.retalix.com/HQLWebServices", IsWrapped=true)]
    public partial class UserLoginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.retalix.com/HQLWebServices", Order=0)]
        public LoyaltyOnlineWSLogin.Status UserLoginResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.retalix.com/HQLWebServices", Order=1)]
        public string out_SessionKey;
        
        public UserLoginResponse()
        {
        }
        
        public UserLoginResponse(LoyaltyOnlineWSLogin.Status UserLoginResult, string out_SessionKey)
        {
            this.UserLoginResult = UserLoginResult;
            this.out_SessionKey = out_SessionKey;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface LoginSoapChannel : LoyaltyOnlineWSLogin.LoginSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class LoginSoapClient : System.ServiceModel.ClientBase<LoyaltyOnlineWSLogin.LoginSoap>, LoyaltyOnlineWSLogin.LoginSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LoginSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(LoginSoapClient.GetBindingForEndpoint(endpointConfiguration), LoginSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LoginSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LoginSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LoginSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LoginSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LoginSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<LoyaltyOnlineWSLogin.UserLoginResponse> UserLoginAsync(LoyaltyOnlineWSLogin.UserLoginRequest request)
        {
            return base.Channel.UserLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task LogOutAsync()
        {
            return base.Channel.LogOutAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LoginSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.LoginSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LoginSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://dev-ws.gorewards.com.ph/LoyaltyOnlineWS/Authorization/Login.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.LoginSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://dev-ws.gorewards.com.ph/LoyaltyOnlineWS/Authorization/Login.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            LoginSoap,
            
            LoginSoap12,
        }
    }
}
